from bot_utils.picture_in_picture.picture_input.picture_input_interface import PictureInputInterface
from bot_utils.picture_in_picture.picture_input.load_image import LoadImage
from bot_utils.picture_in_picture.picture_input.screenshot import Screenshot